server {
    listen 80;
    listen [::]:80;
    server_name 202.61.73.204;
    root /var/www/epsa-elportillo/Epsas/public;
    index index.php;
    charset utf-8;
    client_max_body_size 12m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}