\set ON_ERROR_STOP on

-- Ejecutar como administrador PostgreSQL. Reemplazar la clave antes de usar.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'epsas_app') THEN
        CREATE ROLE epsas_app LOGIN PASSWORD 'REPLACE_WITH_STRONG_PASSWORD';
    END IF;
END
$$;

ALTER ROLE epsas_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE epsas TO epsas_app;
GRANT USAGE ON SCHEMA public TO epsas_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO epsas_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO epsas_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO epsas_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO epsas_app;
